language: generic
services:
  - docker

before_install:
  - docker build -t mottigendave/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mottigendave/react-test npm test

after_success:
  - docker build -t mottigendave/multi-client ./client
  - docker build -t mottigendave/multi-nginx ./nginx
  - docker build -t mottigendave/multi-server ./server
  - docker build -t mottigendave/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mottigendave/multi-client
  - docker push mottigendave/multi-nginx
  - docker push mottigendave/multi-server
  - docker push mottigendave/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-079904198790"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY